### ISSUE TITLE
install.sh fails with unmet dependency diversify-profiling

### ISSUE THREAD

**Issue by paraita** [STAMP-project/dspot#52]
Hi,
I have troubles running the `install.sh` script. I just cloned the repo, chmoded the install script and ran it.
I attached the execution log.
[error_log.txt](https://github.com/STAMP-project/dspot/files/738686/error_log.txt)

**Comment by danglotb** [comment]
Hello,

Thanks you for pointing this bug.

I fixed the version of spoon in the dependencies of DSpot.

It is ok on my side now. Can you please try again, and tell me if you build with success?

Benjamin.

**Comment by paraita** [comment]
Thanks @danglotb for helping me, everything does build fine now but I still encounter some issues during the `mvn test` (see [error_debug_log](https://github.com/STAMP-project/dspot/files/739255/error_debug_log.txt)).
I'd be glad to provide any relevant info :)

**Comment by danglotb** [comment]
Ok, I'm able to have the same errors.

I look for more informations and a fix. I keep you in touch.

Thank you.
