### ISSUE TITLE
Exception in thread "main" spoon.SpoonException: Cannot resolve type erasure of the type parameter reference,  which is not able to found it's declaration

### ISSUE THREAD

**Issue by jesus-gorronogoitia** [STAMP-project/dspot#563]
#### Characteristics
- **Issue Type**: bug,  test report
- **Reproducibility**: always
- **Severity**: major,
- **Tool/Service/Component**: Dspot latest
- **Execution Environment**: Linux Opensuse Tumbleweed
- **Reporter**: Jesús Gorroñogoitia <jesus.gorronogoitia@atos.net>

#### Description
DSpot executed on an Atos Supersede Adapter component with runtime dspot configuration: 
-i 1 -t eu.supersede.dynadapt.modeladapter.test.ModelAdapterTest -a AllLiteralAmplifiers:MethodGeneratorAmplifier:ReturnValueAmplifier:NullifierAmplifier -s JacocoCoverageSelector --timeOut 30000 --verbose

At certain moment in execution, DSpot breaks down with exception:
```
2018-10-01 11:43:44,639 INFO eu.stamp_project.dspot.assertgenerator.MethodsAssertGenerator - Instrumentation...
 69% |================================== ]|Exception in thread "main" spoon.SpoonException: Cannot resolve type erasure of the type parameter reference, which is not able to found it's declaration.
	at spoon.support.reflect.reference.CtTypeParameterReferenceImpl.getTypeErasure(CtTypeParameterReferenceImpl.java:189)
	at spoon.support.reflect.declaration.CtTypeImpl.isSameParameter(CtTypeImpl.java:753)
	at spoon.support.reflect.declaration.CtTypeImpl.hasSameParameters(CtTypeImpl.java:735)
	at spoon.support.reflect.declaration.CtTypeImpl.getMethod(CtTypeImpl.java:719)
	at spoon.support.reflect.reference.CtExecutableReferenceImpl.getCtExecutable(CtExecutableReferenceImpl.java:130)
	at spoon.support.reflect.reference.CtExecutableReferenceImpl.getExecutableDeclaration(CtExecutableReferenceImpl.java:122)
	at spoon.support.reflect.reference.CtTypeParameterReferenceImpl.getDeclaration(CtTypeParameterReferenceImpl.java:143)
	at spoon.support.reflect.reference.CtTypeParameterReferenceImpl.getBoundingType(CtTypeParameterReferenceImpl.java:92)
	at spoon.support.reflect.reference.CtTypeParameterReferenceImpl.getActualClass(CtTypeParameterReferenceImpl.java:62)
	at spoon.support.reflect.reference.CtArrayTypeReferenceImpl.getActualClass(CtArrayTypeReferenceImpl.java:92)
	at spoon.support.reflect.reference.CtTypeReferenceImpl.getTypeDeclaration(CtTypeReferenceImpl.java:185)
	at eu.stamp_project.dspot.assertgenerator.AssertGeneratorHelper.isCorrectReturn(AssertGeneratorHelper.java:49)
	at eu.stamp_project.dspot.assertgenerator.AssertGeneratorHelper.isStmtToLog(AssertGeneratorHelper.java:137)
	at eu.stamp_project.dspot.assertgenerator.AssertGeneratorHelper.lambda$createTestWithLog$0(AssertGeneratorHelper.java:64)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at eu.stamp_project.dspot.assertgenerator.AssertGeneratorHelper.createTestWithLog(AssertGeneratorHelper.java:65)
	at eu.stamp_project.dspot.assertgenerator.MethodsAssertGenerator.lambda$addAssertions$0(MethodsAssertGenerator.java:84)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at eu.stamp_project.dspot.assertgenerator.MethodsAssertGenerator.addAssertions(MethodsAssertGenerator.java:90)
	at eu.stamp_project.dspot.assertgenerator.AssertGenerator.innerAssertionAmplification(AssertGenerator.java:122)
	at eu.stamp_project.dspot.assertgenerator.AssertGenerator.assertionAmplification(AssertGenerator.java:71)
	at eu.stamp_project.dspot.Amplification.assertionsAmplification(Amplification.java:150)
	at eu.stamp_project.dspot.Amplification.amplification(Amplification.java:135)
	at eu.stamp_project.dspot.Amplification.amplification(Amplification.java:97)
	at eu.stamp_project.dspot.DSpot.amplifyTest(DSpot.java:181)
	at eu.stamp_project.dspot.DSpot.amplifyTest(DSpot.java:171)
	at eu.stamp_project.Main.lambda$run$1(Main.java:69)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at eu.stamp_project.Main.run(Main.java:71)
	at eu.stamp_project.Main.main(Main.java:40)

```

#### Steps to reproduce
see #562 for explanation

See full [log](https://github.com/STAMP-project/dspot-usecases-output/blob/master/atos/supersede/JacocoCoverageSelector/AllLiteralAmplifiers-MethodGeneratorAmplifier-ReturnValueAmplifier-NullifierAmplifier/201810011134/nohup.out) of execution.

##### Properties file
Same as in #562 

##### Command Line / Options

```shell
java -jar target/dspot-USED-VERSION-jar-with-dependencies.jar \
-p myPropertiesFile.properties
```

#### [Help on issue template](https://github.com/STAMP-project/dspot/blob/master/.github/ISSUE_DOC.md) 
Preview to follow the link or open file .github/ISSUE_DOC.md

**Comment by danglotb** [comment]
Hi @jesus-gorronogoitia 

In order to investigate, I need to run myself **DSpot** on your project.

However, I tried to build [dyn_adapt](https://github.com/supersede-project/dyn_adapt):
```sh
git clone https://github.com/supersede-project/dyn_adapt.git
cd Maven/eu.supersede.dynadapt/
mvn install -DskipTests
```

But I have the following errors:

```
Non-resolvable parent POM for eu.supersede.dynadapt:eu.supersede.feedbackgathering.reconfiguration.enactor:1.0.0-SNAPSHOT: Could not find artifact eu.supersede.dynadapt:eu.supersede.dynadapt.bundles:pom:1.0.0-SNAPSHOT and &apos;parent.relativePath&apos; points at wrong local POM
```

Where can I find these dependency?

Thanks.

**Comment by jesus-gorronogoitia** [comment]
Hi @danglotb Setting up this project won't be possible for you, at least to run the tests, because they needs to access to services in a server that it is only accessible from Atos (due to strict Atos policies, I am sorry). So, if you need only to setup the problem, I can prepare instructions and required artefacts, but if you need to run the test, that won't be possible. That's why I suggested you to provide me instruccions for further debug DSpot and provide you all debug information. In order words, I can investigate it on behalf you if you provide me instructions or hints about where to look for. Sorry for the inconveniences.

**Comment by danglotb** [comment]
Since the error occurs during the instrumentation, I can skip execution of tests to try to fix the problem. 

Please, provide me the instructions and required artifacts to set up the project. Thank you.

**Comment by jesus-gorronogoitia** [comment]
Ok, I will be preparing the material and documentation as soon as possible. I will keep you informed.

**Comment by jesus-gorronogoitia** [comment]
Hi @danglotb I've prepared some [notes](https://docs.google.com/document/d/1iOPG-yRP4rB1mhBj9mCEwJ4iZYe2z4VZtdDbr9YdcCQ/edit#) to build the Supersede Model Adapter component. I've tested them with a clean Maven repository, so these instructions should work for you. Let me know, please.

**Comment by andrewbwogi** [comment]
Hi @jesus-gorronogoitia, 

I'm trying to reproduce the problem but I run into errors in step 3 of your instructions. YAFMT compiles but not Supersede dynamic adaptation plugins. Using a clean local Maven repository and having run installPom.sh in both cz.zcu.yafmt.configuration and eu.supersede.dynadapt.configuration, buildEclipseDependencies.sh gives the following kind of errors:

```
Non-resolvable parent POM for eu.supersede.dynadapt:eu.supersede.dynadapt.aom.dsl:1.0.0-SNAPSHOT: Could not find artifact eu.supersede.dynadapt:eu.supersede.dynadapt.bundles:pom:1.0.0-SNAPSHOT and 'parent.relativePath' points at wrong local POM
```
All errors are here: [build-trace.txt](https://github.com/STAMP-project/dspot/files/2453985/build-trace.txt)

**Comment by jesus-gorronogoitia** [comment]
Hi @andrewbwogi 
Please, tell me the Maven version you are using and your OS. I followed the given instructions in a clean Maven installation and it worked well for me, so I will do it all over again. I will keep you informed.
Regards
Yosu

**Comment by jesus-gorronogoitia** [comment]
Hi @andrewbwogi 
I've just test it again using a clean Maven repository and Maven  3.3.9 on Linux, without any trouble. 
I assume you are blocked in step 3.

I've just done this:
`git clone https://github.com/supersede-project/dyn_adapt.git -b stamp-baseline`
This creates the folder $dyn_adapt. In next steps replace $dyn_adapt with the path to that folder:
```
cd $dyn_adapt/Maven/eu.supersede.dynadapt/releng/eu.supersede.dynadapt.configuration/ 
./installPom.sh
cd $dyn_adapt/Maven/cz.zcu.yafmt/releng/cz.zcu.yafmt.configuration/
./installPom.sh
cd $dyn_adapt
./buildEclipseDependencies.sh
```
I am going to try again with latest Maven plugin, just in case.
Regards
Yosu

**Comment by jesus-gorronogoitia** [comment]
Hi @andrewbwogi I've fixed this problem, updating the Tycho plugin we use to build the software. No, it works well with Maven 3.5.4. Please pull the repository and try again.

**Comment by andrewbwogi** [comment]
I managed to build the project successfully with Maven 3.3.9 but with Maven 3.5.4 I still get the same error.

**Comment by jesus-gorronogoitia** [comment]
Uhm, I will double check, It worked for me. Anyway, you succeeded on building the project, so I guess you can investigate what's going on when using DSpot on it.

**Comment by andrewbwogi** [comment]
Hi @jesus-gorronogoitia, DSpot is attempting to run the ModelAdapterTest but it produces the following error: 
```
I/O error on GET request for 
"http://supersede.es.atos.net:8280/modelrepositorymanager/models/BaseModel": 
Connection timed out (Connection timed out); 
nested exception is java.net.ConnectException: Connection timed out (Connection timed out)
```

Is this related to the accessibility of Atos servers? DSpot needs to run the tests to generate new tests.

**Comment by jesus-gorronogoitia** [comment]
Hi @andrewbwogi, yes it is caused because you have not access to Atos server and there is nothing to do about. I can do experiments for you and report you all the information you may need to debug this issue.
